# Generated by Django 4.2 on 2026-04-21 14:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(default=api.models.generate_short_id, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
